unbind r
bind r source-file ~/.config/tmux/tmux.conf 

set -g prefix C-space

set -g mouse on
set -g status-position bottom

# Use Alt + hjkl to move between panes (vim-style)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
 
# Always split in same directory
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

set-option -g message-command-style 'bg=#282c34,fg=#bbc2cf'
set-option -g message-style 'bg=#282c34,fg=#bbc2cf'
set-option -g mode-style 'bg=#424856'
set-option -g status-justify left 
set-option -g status-right 'session: #S '
set-option -g status-right-length 32 
set-option -g status-right-style 'bold'
set-option -g status-left-length 32 
set-option -g status-left-style 'bold'
set-option -g status-style 'bg=#1b2229,fg=#bbc2cf'
set-option -g window-status-current-format ' [#I] #W ' 
set-option -g window-status-current-style 'bg=#51afef,fg=#282c34'
set-option -g window-status-format ' [#I] #W '
set-option -g window-status-separator ' '
set-option -g window-status-style ''

# run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
#set -g @catppuccin_status_background "none"
#
#set-option -g automatic-rename off
#set-option -g allow-rename off
#
#set -g status-left ""
#set -g status-right "#{E:@catppuccin_status_session}"
#
#set -g @catppuccin_window_status_style "slanted"
#
#set -g @catppuccin_window_text " #W"
#set -g @catppuccin_window_current_text " #W"
#
#set -g @catppuccin_window_current_number "Tab #I"
#set -g @catppuccin_window_number "Tab #I"

# Let tmux know kitty supports cursor-shape changes
set -as terminal-features 'xterm-kitty:ccc'

# Tell tmux how to pass cursor-shape escape sequences through
set -g terminal-overrides ',xterm-kitty:Ss=\E[%p1%d q:Se='

